# Generated by Django 3.2.15 on 2022-08-27 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("cover", models.BooleanField(default=False)),
                (
                    "roughs",
                    models.ImageField(
                        blank=True,
                        default="../default-page_xo6mbk",
                        upload_to="images/",
                    ),
                ),
                (
                    "inks",
                    models.ImageField(
                        blank=True,
                        default="../default-page_xo6mbk",
                        upload_to="images/",
                    ),
                ),
                (
                    "colors",
                    models.ImageField(
                        blank=True,
                        default="../default-page_xo6mbk",
                        upload_to="images/",
                    ),
                ),
                (
                    "letters",
                    models.ImageField(
                        blank=True,
                        default="../default-page_xo6mbk",
                        upload_to="images/",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
