# Generated by Django 3.2.15 on 2022-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_page_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["page_number"]},
        ),
        migrations.AddField(
            model_name="page",
            name="page_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
